# Generated by Django 4.2.1 on 2023-05-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_product_alter_category_id_alter_image_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="product",),
    ]
