# Generated by Django 4.2.1 on 2023-06-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.IntegerField(
                choices=[(0, "No"), (1, "Everywhere"), (2, "Category")], default=0
            ),
        ),
    ]
