# Generated by Django 4.2.1 on 2023-06-04 14:26

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "430x360",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
    ]
